In [0]:
### Databricks - PySpark io

In [0]:
df1 = spark.read.format("csv").load("dbfs:/FileStore/shared_uploads/andrewnaffer3@gmail.com/marca_carro.csv")
df2 = spark.read.format("csv").load("dbfs:/FileStore/shared_uploads/andrewnaffer3@gmail.com/marcas_duplicadas.csv")
df3 = spark.read.format("csv").load("dbfs:/FileStore/shared_uploads/andrewnaffer3@gmail.com/modelo_carro.csv")
df3.count()

Out[78]: 1001

In [0]:
df3.head(5)
#display(df3)

Out[79]: [Row(_c0='id_carro', _c1='modelo_carro', _c2='preco', _c3='cod_marca'),
 Row(_c0='1', _c1='Avalon', _c2='$78401.95', _c3='54'),
 Row(_c0='2', _c1='RDX', _c2='$95987.38', _c3='1'),
 Row(_c0='3', _c1='Golf', _c2='$61274.55', _c3='55'),
 Row(_c0='4', _c1='EX', _c2='$84981.12', _c3='23')]

In [0]:
df3.write.format("csv").mode("overwrite").save("/aprendizado/mode_carro")
df2.write.format("csv").mode("overwrite").save("/aprendizado/marcas_duplicadas")
df1.write.format("csv").mode("overwrite").save("/aprendizado/marca_carro")

In [0]:
df_carro = spark.read.format("csv").load("/aprendizado/mode_carro")
print(df_carro.count())

1001

In [0]:
df_carro.head(5)
#display(df_carro)

Out[82]: [Row(_c0='id_carro', _c1='modelo_carro', _c2='preco', _c3='cod_marca'),
 Row(_c0='1', _c1='Avalon', _c2='$78401.95', _c3='54'),
 Row(_c0='2', _c1='RDX', _c2='$95987.38', _c3='1'),
 Row(_c0='3', _c1='Golf', _c2='$61274.55', _c3='55'),
 Row(_c0='4', _c1='EX', _c2='$84981.12', _c3='23')]

In [0]:
df_carros = spark.read.format("csv").option("header", True).load("/aprendizado/mode_carro", sep = ",")
df_carro.head(5)
#display(df_carro)

Out[83]: [Row(_c0='id_carro', _c1='modelo_carro', _c2='preco', _c3='cod_marca'),
 Row(_c0='1', _c1='Avalon', _c2='$78401.95', _c3='54'),
 Row(_c0='2', _c1='RDX', _c2='$95987.38', _c3='1'),
 Row(_c0='3', _c1='Golf', _c2='$61274.55', _c3='55'),
 Row(_c0='4', _c1='EX', _c2='$84981.12', _c3='23')]

In [0]:
## Visualizando os dados usando comandos SQL

df_carros.createOrReplaceTempView("carros")
df_carros_sql = spark.sql("""
SELECT 
modelo_carro AS modelo, id_carro
FROM
carros
""")
df_carros_sql.head(5)
#display(df_carros_sql)

Out[84]: [Row(modelo='Avalon', id_carro='1'),
 Row(modelo='RDX', id_carro='2'),
 Row(modelo='Golf', id_carro='3'),
 Row(modelo='EX', id_carro='4'),
 Row(modelo='Escort', id_carro='5')]

In [0]:
df_carros_spark = df_carros.selectExpr("modelo_carro AS modelo", "id_carro")
df_carros_spark.head(5)
#display(df_carros_spark)

Out[85]: [Row(modelo='Avalon', id_carro='1'),
 Row(modelo='RDX', id_carro='2'),
 Row(modelo='Golf', id_carro='3'),
 Row(modelo='EX', id_carro='4'),
 Row(modelo='Escort', id_carro='5')]

In [0]:
from pyspark.sql.functions import col
df_carros_spark1 = df_carros.select(col("modelo_carro").alias("modelo"), "id_carro")
df_carros_spark1.head(5)
#display(df_carros_spark1)

Out[86]: [Row(modelo='Avalon', id_carro='1'),
 Row(modelo='RDX', id_carro='2'),
 Row(modelo='Golf', id_carro='3'),
 Row(modelo='EX', id_carro='4'),
 Row(modelo='Escort', id_carro='5')]

In [0]:
# Filtros com SQL
df_carro_01 = spark.read.format("csv").option("header", True).load("/aprendizado/mode_carro")

In [0]:
df_carro_01.createOrReplaceTempView("carros")
df_carros_sql01 = spark

In [0]:
%sql
SELECT * FROM carros
WHERE id_carro = 1
AND modelo_carro = "Avalon"

id_carro,modelo_carro,preco,cod_marca
1,Avalon,$78401.95,54

In [0]:
from pyspark.sql.functions import col

display(
    df_carro_01.where(
        (col("id_carro") == "1") &
        (col("modelo_carro") == "Avalon")
)
        )

id_carro,modelo_carro,preco,cod_marca
1,Avalon,$78401.95,54

In [0]:
df_carros = spark.read.format("csv").option("header", True).load("/aprendizado/mode_carro")
display(df_carros.where("id_carro = '1'"))
df_carros.createOrReplaceTempView("carros")

id_carro,modelo_carro,preco,cod_marca
1,Avalon,$78401.95,54